[development]
NODE_ENV_MONGO_HOST=<ip>
NODE_ENV_MONGO_PORT=<port>
NODE_ENV_MONGO_DATABASE=linkpin
DOCKER_ENV_VOLUME_MONGOBACKUP=/Users/<username>
DOCKER_ENV_PORTS=3030:3030

[production]
NODE_ENV_MONGO_HOST=mongo
NODE_ENV_MONGO_PORT=27017
NODE_ENV_MONGO_DATABASE=linkpin
DOCKER_ENV_VOLUME_MONGOBACKUP=/usr/local
DOCKER_ENV_PORTS=80:3030
