[development]
NODE_ENV_MONGO_HOST=<ip>
NODE_ENV_MONGO_PORT=<port>
NODE_ENV_MONGO_DATABASE=linkpin

DOCKER_ENV_PORTS=3030:3030
DOCKER_ENV_VOLUME_MONGOBACKUP=/Users/<username>
#Hourly cron execution
MONGOBACKUP_BACKUP_CRON=

[production]
NODE_ENV_MONGO_HOST=mongo
NODE_ENV_MONGO_PORT=27017
NODE_ENV_MONGO_DATABASE=linkpin

DOCKER_ENV_PORTS=80:3030
DOCKER_ENV_VOLUME_MONGOBACKUP=/usr/local
#Daily cron execution
MONGOBACKUP_BACKUP_CRON=0 2 * * *
